package database;

public class ScriptDDL {

    public static String getCreateTableGnrTipoAvaliacao(){

        StringBuilder sql = new StringBuilder();

        sql.append("CREATE TABLE GNR_TIPO_AVALIACAO (CODIGO_TIPO_AVALIACAO SERIAL, DESCRICAO_GNR_TIPO_AVALIACAO VARCHAR(100),PRIMARY KEY (CODIGO_TIPO_AVALIACAO));");

        return sql.toString();

    }

    public static String getCreateTableGnrRespostasAlunos(){

        StringBuilder sql = new StringBuilder();

        sql.append("CREATE TABLE GNR_RESPOSTAS_ALUNOS (CODIGO_GNR_RESPOSTAS_ALUNOS INTEGER, DATA_GNR_RESPOSTAS_ALUNOS INTEGER UNIQUE,GNR_ALUNO_MATRICULA_GNR_ALUNO INTEGER UNIQUE,PRIMARY KEY (CODIGO_GNR_RESPOSTAS_ALUNOS));");

        return sql.toString();

    }

    public static String getCreateTableGnrRespostasAlunositens(){

        StringBuilder sql = new StringBuilder();

        sql.append("CREATE TABLE GNR_RESPOSTAS_ALUNOS_ITENS( RESPOSTA_GNR_RESPOSTAS_ITENS VARCHAR, GNR_RESPOSTAS_ALUNOS_CODIGO_GNR_ALUNOS INTEGER, GNR_PERGUNTAS_CODIGO_GNR_PERGUNTAS INTEGER UNIQUE, FOREIGN KEY (GNR_RESPOSTAS_ALUNOS_CODIGO_GNR_ALUNOS) REFERENCES GNR_RESPOSTAS_ALUNOS (DATA_GNR_RESPOSTAS_ALUNOS));");

        return sql.toString();

    }

    public static String getCreateTableGnrAluno(){

        StringBuilder sql = new StringBuilder();

        sql.append("CREATE TABLE GNR_ALUNO ( MATRICULA_GNR_ALUNO SERIAL, NOME_GNR_ALUNO VARCHAR(200), LOGIN_GNR_ALUNO VARCHAR(45), EMAIL_GNR_ALUNO VARCHAR(200), PERIODO_GNR_ALUNO VARCHAR(45), PRIMARY KEY (MATRICULA_GNR_ALUNO), FOREIGN KEY (MATRICULA_GNR_ALUNO) REFERENCES GNR_RESPOSTAS_ALUNOS (GNR_ALUNO_MATRICULA_GNR_ALUNO));");

        return sql.toString();

    }

    public static String getCreateTableGnrPerguntas(){

        StringBuilder sql = new StringBuilder();

        sql.append("CREATE TABLE GNR_PERGUNTAS ( CODIGO_GNR_PERGUNTAS SERIAL, DESCRICAO_GNR_PERGUNTAS VARCHAR(500), GNR_CLASSIFICACAO_PERGUNTAS_CODIGO_GNR_CLASSIFICAO_PERGUNTAS INTEGER UNIQUE, GNR_MODELO_RESPOSTAS_CODIGO_GNR_RESPOSTAS INTEGER UNIQUE, PRIMARY KEY (CODIGO_GNR_PERGUNTAS), FOREIGN KEY (GNR_CLASSIFICACAO_PERGUNTAS_CODIGO_GNR_CLASSIFICAO_PERGUNTAS) REFERENCES GNR_RESPOSTAS_ALUNOS_ITENS (GNR_PERGUNTAS_CODIGO_GNR_PERGUNTAS));");

        return sql.toString();

    }

    public static String getCreateTableGnrClassificacaoPerguntas(){

        StringBuilder sql = new StringBuilder();

        sql.append("CREATE TABLE GNR_CLASSIFICACAO_PERGUNTAS ( CODIGO_GNR_CLASSIFICACAO_PERGUNTAS SERIAL, DESCRICAO_GNR_CLASSIFICACAO_PERGUNTAS VARCHAR(200), PRIMARY KEY (CODIGO_GNR_CLASSIFICACAO_PERGUNTAS), FOREIGN KEY (CODIGO_GNR_CLASSIFICACAO_PERGUNTAS) REFERENCES GNR_PERGUNTAS (GNR_CLASSIFICACAO_PERGUNTAS_CODIGO_GNR_CLASSIFICAO_PERGUNTAS));");

        return sql.toString();

    }

    public static String getCreateTableGnrModeloRespostas(){

        StringBuilder sql = new StringBuilder();

        sql.append("CREATE TABLE GNR_MODELO_RESPOSTAS ( CODIGO_GNR_MODELO_RESPOSTAS SERIAL, DESCRICAO_GNR_MODELO_RESPOSTAS VARCHAR(45), PRIMARY KEY (CODIGO_GNR_MODELO_RESPOSTAS), FOREIGN KEY (CODIGO_GNR_MODELO_RESPOSTAS) REFERENCES GNR_PERGUNTAS (GNR_MODELO_RESPOSTAS_CODIGO_GNR_RESPOSTAS));");

        return sql.toString();

    }
}
